-- Saved by UniversalSynSaveInstance (Join to Copy Games) https://discord.gg/wx4ThpAsmw

-- Bytecode (Base64):
-- CQMOBGdhbWURUmVwbGljYXRlZFN0b3JhZ2UKR2V0U2VydmljZQdyZXF1aXJlB0xpYnJhcnkHTW9kdWxlcwhQYWNrYWdlcwF0BXR1cGxlBXVuaW9uBnN0cmluZwV0YWJsZQNtYXAPVXBkYXRlTW9kaWZpZXJzAAEIAAABAgAoowAAAKQAAQAAAABAbwICALwAABYDAAAAnwADAqQBBQAAAEBATQIAagYAAABNAgLoBwAAAE0CAuYIAAAATQIClQkAAACfAQIC/wIBAAAAAABNAwF4CgAAAE0EAZgLAAAATQUBQQwAAABNBgFLDQAAAJ8EAwJNBQGQDgAAAE0GAUEMAAAATQcBSw0AAACfBQMAnwMAAjADAoQPAAAAggICABADAQQAAABAAwIDAwMEBAAAQEADBQMGAwcDCAMJAwoDCwMMAw0DDgABAAEYAAEAAAAAAAMAAAAAAAAAAAAACAACAAAAAAAAAAAAAAAAAAAAAAAAAgEAAAAAAJadwd8vVs5ahJkjUMJh1JfmhdarpFmr3g==

-- decompilation:
local ReplicatedStorage = game:GetService("ReplicatedStorage")
local t = require(ReplicatedStorage.Library.Modules.Packages.t)

return {
	UpdateModifiers = t.tuple(t.union(t.string, t.table), t.map(t.string, t.table))
}

