-- Saved by UniversalSynSaveInstance (Join to Copy Games) https://discord.gg/wx4ThpAsmw

-- Bytecode (Base64):
-- CQMKBGdhbWURUmVwbGljYXRlZFN0b3JhZ2UKR2V0U2VydmljZQdyZXF1aXJlBnNjcmlwdAZQYXJlbnQGU2NoZW1hB0xpYnJhcnkFVHlwZXMJRnJlZUdpZnRzAAEEAAABAgAaowAAAKQAAQAAAABAbwICALwAABYDAAAAnwADAqQBBQAAAEBApAIHAAAAYEBNAgIkCAAAAE0CAv4JAAAAnwECAqQCBQAAAEBATQMAagoAAABNAwPvCwAAAE0DA7EMAAAAnwICAoIBAgANAwEEAAAAQAMCAwMDBAQAAEBAAwUEAABgQAMGAwcDCAMJAwoAAQABGAADAAAAAAADAAAAAAAAAAABAAAAAAAAAAALAQAAAAAAwVrZFfIceXAHA7VBEWuIR7FCzmHznrMU

-- decompilation:
local ReplicatedStorage = game:GetService("ReplicatedStorage")
local Schema = require(script.Parent.Schema)

require(ReplicatedStorage.Library.Types.FreeGifts)

return Schema

