-- Saved by UniversalSynSaveInstance (Join to Copy Games) https://discord.gg/wx4ThpAsmw

-- Bytecode (Base64):
-- CQMJBGdhbWURUmVwbGljYXRlZFN0b3JhZ2UKR2V0U2VydmljZQdyZXF1aXJlB0xpYnJhcnkGQ2xpZW50GFRyZWFkbWlsbFZpZGVvQ29udHJvbGxlcgVUeXBlcwlJbnRlcmZhY2UAAQMAAAECABajAAAApAABAAAAAEBvAgIAvAAAFgMAAACfAAMCpAEFAAAAQEBNAgBqBgAAAE0CAk0HAAAATQICqQgAAABNAgLvCQAAAE0CAg8KAAAAnwECAsYCAACCAgIACwMBBAAAAEADAgMDAwQEAABAQAMFAwYDBwMIAwkAAQABGAADAAAAAAADAAAAAAAAAAAAAAAADAABAAAAAAAJFlWsPRjBL+SvghkvTf34eQ5C2DvSP60=

-- decompilation:
local ReplicatedStorage = game:GetService("ReplicatedStorage")

require(ReplicatedStorage.Library.Client.TreadmillVideoController.Types.Interface)

return nil

