-- Saved by UniversalSynSaveInstance (Join to Copy Games) https://discord.gg/wx4ThpAsmw

-- Bytecode (Base64):
-- CQMLBGdhbWURUmVwbGljYXRlZFN0b3JhZ2UKR2V0U2VydmljZQdyZXF1aXJlBnNjcmlwdAZQYXJlbnQGU2NoZW1hB0xpYnJhcnkJRHJvcFRhYmxlBUl0ZW1zDEN1cnJlbmN5SXRlbQABBQAAAQIAIaMAAACkAAEAAAAAQG8CAgC8AAAWAwAAAJ8AAwKkAQUAAABAQKQCBwAAAGBATQICJAgAAABNAgL+CQAAAJ8BAgKkAgUAAABAQE0DAGoKAAAATQMDfQsAAACfAgICpAMFAAAAQEBNBABqCgAAAE0EBDgMAAAATQQEkQ0AAACfAwICggECAA4DAQQAAABAAwIDAwMEBAAAQEADBQQAAGBAAwYDBwMIAwkDCgMLAAEAARgAAwAAAAAAAwAAAAAAAAAAAQAAAAAAAAEAAAAAAAAAACQBAAAAAACUgjlrIsU42yzFUCFDryf05JouH6ZGU2o=

-- decompilation:
local ReplicatedStorage = game:GetService("ReplicatedStorage")
local Schema = require(script.Parent.Schema)

require(ReplicatedStorage.Library.DropTable)
require(ReplicatedStorage.Library.Items.CurrencyItem)

return Schema

