-- Saved by UniversalSynSaveInstance (Join to Copy Games) https://discord.gg/wx4ThpAsmw

-- Bytecode (Base64):
-- CQMJBGdhbWURUmVwbGljYXRlZFN0b3JhZ2UKR2V0U2VydmljZQdyZXF1aXJlBnNjcmlwdAZQYXJlbnQJSW50ZXJmYWNlB0xpYnJhcnkFQXVkaW8AAQQAAAECABmjAAAApAABAAAAAEBvAgIAvAAAFgMAAACfAAMCpAEFAAAAQECkAgcAAABgQE0CAiQIAAAATQICDwkAAACfAQICpAIFAAAAQEBNAwBqCgAAAE0DA9ILAAAAnwICAsYDAACCAwIADAMBBAAAAEADAgMDAwQEAABAQAMFBAAAYEADBgMHAwgDCQABAAEYAAMAAAAAAAMAAAAAAAAAAAEAAAAAAACSAAEAAAAAABAdFB9Igx5fMCvTOXkcrIRgBQNrItl+Hg==

-- decompilation:
local ReplicatedStorage = game:GetService("ReplicatedStorage")

require(script.Parent.Interface)
require(ReplicatedStorage.Library.Audio)

return nil

