-- Saved by UniversalSynSaveInstance (Join to Copy Games) https://discord.gg/wx4ThpAsmw

-- Bytecode (Base64):
-- CQMLBGdhbWURUmVwbGljYXRlZFN0b3JhZ2UKR2V0U2VydmljZQdyZXF1aXJlCURpcmVjdG9yeQpBbmltYXRpb25zCFBpcGVsaW5lBlJhcml0eQZzY3JpcHQGUGFyZW50BlNjaGVtYQABBQAAAQIAIaMAAACkAAEAAAAAQG8CAgC8AAAWAwAAAJ8AAwKkAQUAAABAQE0CAJEGAAAATQICRAcAAABNAgI5CAAAAJ8BAgKkAgUAAABAQE0DAJEGAAAATQMD8gkAAACfAgICpAMFAAAAQECkBAsAAACgQE0EBCQMAAAATQQE/g0AAACfAwICggMCAA4DAQQAAABAAwIDAwMEBAAAQEADBQMGAwcDCAMJBAAAoEADCgMLAAEAARgAAwAAAAAAAwAAAAAAAAAAAQAAAAAAAAEAAAAAAAAAACUBAAAAAABjyITq2ofgXdX95Z9tZ9GYE9CTnlEM7us=

-- decompilation:
local ReplicatedStorage = game:GetService("ReplicatedStorage")

require(ReplicatedStorage.Directory.Animations.Pipeline)
require(ReplicatedStorage.Directory.Rarity)

return (require(script.Parent.Schema))

