-- Saved by UniversalSynSaveInstance (Join to Copy Games) https://discord.gg/wx4ThpAsmw

-- Bytecode (Base64):
-- CQMHEGJpbmRhYmxlUmVzb3VyY2UEQ21kcgRVdGlsDE1ha2VFbnVtVHlwZRBCaW5kYWJsZVJlc291cmNlBENoYXQMUmVnaXN0ZXJUeXBlAAIIAQAAAAASbwMAAE0EAJ4BAAAATQQEngIAAABNBASyAwAAAG8FBAD/BgAAAQAAAG8HBQDFBgcCAQAAAJ8EAwC8AQDdBgAAAJ8BAAGCAAEABwMBAwIDAwMEAwUDBgMHAAEAARgAAAAAAAAAAAAAAAAAAAAAAAECAAAAAAEAAAECAAOjAAAAwAAAAIIAAgABBgABAAEAARgAAAABAAAAAAE=

-- decompilation:
return function(p1) -- line: 1
	p1:RegisterType("bindableResource", p1.Cmdr.Util.MakeEnumType("BindableResource", { "Chat" }))
end

