-- Saved by UniversalSynSaveInstance (Join to Copy Games) https://discord.gg/wx4ThpAsmw

-- Bytecode (Base64):
-- CQMMBE5hbWUFZmV0Y2gHQWxpYXNlcwtEZXNjcmlwdGlvbh9GZXRjaCBhIHZhbHVlIGZyb20gdGhlIEludGVybmV0BUdyb3VwDERlZmF1bHREZWJ1ZwRBcmdzBFR5cGUDdXJsA1VSTBFUaGUgVVJMIHRvIGZldGNoLgABAwAAAQIADqMAAADiAAgA/wEAAAAAAAAwAQAnAgAAAP8BAAABAAAA4gINAMUBAgIBAAAAMAEA2wcAAACCAAIADgMBAwIDAwMEAwUDBgMHAwgIBQABAAAAAv////8DBAAAAAUGAAAAB/////8DCQMKAwsDDAgDCQoAAAAACwAAAAMMAAAAAAEAARgAAAIAAAADAAEAAP8AAAEAAAAAALOkXo/RHylUZ82uKU5SqpDDvEn7gWA0jg==

-- decompilation:
return {
	Name = "fetch",
	Description = "Fetch a value from the Internet",
	Group = "DefaultDebug",
	Aliases = {},
	Args = {{
		Type = "url",
		Name = "URL",
		Description = "The URL to fetch."
	}}
}

