-- Saved by UniversalSynSaveInstance (Join to Copy Games) https://discord.gg/wx4ThpAsmw

-- Bytecode (Base64):
-- CQMNBE5hbWUDZmx5C0Rlc2NyaXB0aW9uGUFsbG93cyB0aGUgcGxheWVyIHRvIGZseS4HQWxpYXNlcwVHcm91cAVBZG1pbgRBcmdzAARUeXBlB3BsYXllcnMGUGxheWVyGkdyYW50cyB0aGUgYWJpbGl0eSB0byBmbHkuAAEDAAABAgARowAAAOIACAD/AQAAAQAAAG8CCQDFAQICAQAAADABACcEAAAA/wEAAAEAAADiAg4AxQECAgEAAAAwAQDbBwAAAIIAAgAPAwEDAgMDAwQDBQMGAwcDCAgFAAEAAAACAwAAAAT/////BQYAAAAH/////wMJAwoDCwMMAw0IAwoLAAAAAAwAAAACDQAAAAABAAEYAAADAAAAAAAAAgABAAD/AAABAAAAAADgVgLTz5j+SWHcDMvlUTpFkE4Vp9KSaNI=

-- decompilation:
return {
	Name = "fly",
	Description = "Allows the player to fly.",
	Group = "Admin",
	Aliases = { "" },
	Args = {{
		Type = "players",
		Name = "Player",
		Description = "Grants the ability to fly."
	}}
}

