-- Saved by UniversalSynSaveInstance (Join to Copy Games) https://discord.gg/wx4ThpAsmw

-- Bytecode (Base64):
-- CQMLBE5hbWUWZ2xvYmFsU3RhcnRHcm93dGhCb29zdAtEZXNjcmlwdGlvbiRTdGFydCBhbiBncm93dGggYm9vc3QgaW4gYWxsIHNlcnZlcnMFR3JvdXAJTW9kZXJhdG9yBEFyZ3MEVHlwZQdpbnRlZ2VyCER1cmF0aW9uCk11bHRpcGxpZXIAAQQAAAECAAujAAAA4gAHAP8BAAACAAAA4gILAOIDDQDFAQIDAQAAADABANsGAAAAggACAA4DAQMCAwMDBAMFAwYDBwgEAAEAAAACAwAAAAQFAAAABv////8DCAMJAwoIAggJAAAAAAoAAAADCwgCCAkAAAAADAAAAAABAAEYAAAEAAEBAAD+AAABAAAAAACB2IfH7qdB4Z6yiKF5AOtp8cCQs7Mc7cY=

-- decompilation:
return {
	Name = "globalStartGrowthBoost",
	Description = "Start an growth boost in all servers",
	Group = "Moderator",
	Args = {
		{
			Type = "integer",
			Name = "Duration"
		},
		{
			Type = "integer",
			Name = "Multiplier"
		}
	}
}

