-- Saved by UniversalSynSaveInstance (Join to Copy Games) https://discord.gg/wx4ThpAsmw

-- Bytecode (Base64):
-- CQMMBE5hbWUQZ2xvYmFsU3RhcnRFdmVudAtEZXNjcmlwdGlvbh1TdGFydCBhbiBldmVudCBpbiBhbGwgc2VydmVycwVHcm91cAlNb2RlcmF0b3IEQXJncwRUeXBlDmFkbWluRXZlbnRUeXBlCkV2ZW50IE5hbWUGbnVtYmVyCER1cmF0aW9uAAEEAAABAgALowAAAOIABwD/AQAAAgAAAOICCwDiAw4AxQECAwEAAAAwAQDbBgAAAIIAAgAPAwEDAgMDAwQDBQMGAwcIBAABAAAAAgMAAAAEBQAAAAb/////AwgDCQMKCAIICQAAAAAKAAAAAwsDDAgCCAwAAAAADQAAAAABAAEYAAAEAAEBAAD+AAABAAAAAACOen29SSp0vnkSgNg0oANH/mJqyby+F7w=

-- decompilation:
return {
	Name = "globalStartEvent",
	Description = "Start an event in all servers",
	Group = "Moderator",
	Args = {
		{
			Type = "adminEventType",
			Name = "Event Name"
		},
		{
			Type = "number",
			Name = "Duration"
		}
	}
}

