-- Saved by UniversalSynSaveInstance (Join to Copy Games) https://discord.gg/wx4ThpAsmw

-- Bytecode (Base64):
-- CQMLBE5hbWUaZ2xvYmFsUHJvZ3Jlc3NFZ2dIYXRjaFRpbWULRGVzY3JpcHRpb24wSW5jcmVtZW50cyB0aGUgaGF0Y2ggdGltZSBvbiBhbGwgdGhlIHBsYWNlZCBlZ2dzBUdyb3VwCU1vZGVyYXRvcgRBcmdzBFR5cGUHaW50ZWdlcgZBbW91bnQkVGhlIGFtb3VudCBvZiBoYXRjaCB0aW1lIHRvIHByb2dyZXNzAAEDAAABAgAKowAAAOIABwD/AQAAAQAAAOICDADFAQICAQAAADABANsGAAAAggACAA0DAQMCAwMDBAMFAwYDBwgEAAEAAAACAwAAAAQFAAAABv////8DCAMJAwoDCwgDCAkAAAAACgAAAAILAAAAAAEAARgAAAQAAQAA/wAAAQAAAAAALCsC08kDhnvdX5ZRNvF8TVwzFace72jS

-- decompilation:
return {
	Name = "globalProgressEggHatchTime",
	Description = "Increments the hatch time on all the placed eggs",
	Group = "Moderator",
	Args = {{
		Type = "integer",
		Name = "Amount",
		Description = "The amount of hatch time to progress"
	}}
}

