-- Saved by UniversalSynSaveInstance (Join to Copy Games) https://discord.gg/wx4ThpAsmw

-- Bytecode (Base64):
-- CQMHBE5hbWUSZ2xvYmFsTGlzdFNjaGVkdWxlC0Rlc2NyaXB0aW9uGVByaW50cyB0aGUgZXZlbnQgc2NoZWR1bGUFR3JvdXAJTW9kZXJhdG9yBEFyZ3MAAQIAAAECAAejAAAA4gAHAP8BAAAAAAAAMAEA2wYAAACCAAIACAMBAwIDAwMEAwUDBgMHCAQAAQAAAAIDAAAABAUAAAAG/////wABAAEYAAAEAAAAAAEAAAAAAA==

-- decompilation:
return {
	Name = "globalListSchedule",
	Description = "Prints the event schedule",
	Group = "Moderator",
	Args = {}
}

