-- Saved by UniversalSynSaveInstance (Join to Copy Games) https://discord.gg/wx4ThpAsmw

-- Bytecode (Base64):
-- CQMKBE5hbWUPZ2xvYmFsU3RvcEV2ZW50C0Rlc2NyaXB0aW9uG1N0b3BzIGV2ZW50cyBpbiBhbGwgc2VydmVycwVHcm91cAlNb2RlcmF0b3IEQXJncwRUeXBlDmFkbWluRXZlbnRUeXBlCkV2ZW50IE5hbWUAAQMAAAECAAqjAAAA4gAHAP8BAAABAAAA4gILAMUBAgIBAAAAMAEA2wYAAACCAAIADAMBAwIDAwMEAwUDBgMHCAQAAQAAAAIDAAAABAUAAAAG/////wMIAwkDCggCCAkAAAAACgAAAAABAAEYAAAEAAEAAP8AAAEAAAAAAA==

-- decompilation:
return {
	Name = "globalStopEvent",
	Description = "Stops events in all servers",
	Group = "Moderator",
	Args = {{
		Type = "adminEventType",
		Name = "Event Name"
	}}
}

