-- Saved by UniversalSynSaveInstance (Join to Copy Games) https://discord.gg/wx4ThpAsmw

-- Bytecode (Base64):
-- CQMQBE5hbWUJanVtcHBvd2VyC0Rlc2NyaXB0aW9uIFNldHMgdGhlIGp1bXAgcG93ZXIgb2YgYSBwbGF5ZXIuB0FsaWFzZXMFR3JvdXAGVGVzdGVyBEFyZ3MCanAEVHlwZQdwbGF5ZXJzBlBsYXllcidUaGUgcGxheWVycyB0byBjaGFuZ2UgdGhlIGp1bXAgcG93ZXIgb2YGbnVtYmVyBXBvd2VyGlRoZSBqdW1wcG93ZXIgdmFsdWUgdG8gc2V0AAEEAAABAgASowAAAOIACAD/AQAAAQAAAG8CCQDFAQICAQAAADABACcEAAAA/wEAAAIAAADiAg4A4gMSAMUBAgMBAAAAMAEA2wcAAACCAAIAEwMBAwIDAwMEAwUDBgMHAwgIBQABAAAAAgMAAAAE/////wUGAAAAB/////8DCQMKAwsDDAMNCAMKCwAAAAAMAAAAAg0AAAADDgMPAxAIAwoPAAAAABAAAAACEQAAAAABAAEYAAIDAAAAAAAAAgABBQAA+gAAAQAAAAAADlkc0Or8N7yL57oJetAc335BC6Q8nXbR

-- decompilation:
return {
	Name = "jumppower",
	Description = "Sets the jump power of a player.",
	Group = "Tester",
	Aliases = { "jp" },
	Args = {
		{
			Type = "players",
			Name = "Player",
			Description = "The players to change the jump power of"
		},
		{
			Type = "number",
			Name = "power",
			Description = "The jumppower value to set"
		}
	}
}

