-- Saved by UniversalSynSaveInstance (Join to Copy Games) https://discord.gg/wx4ThpAsmw

-- Bytecode (Base64):
-- CQMLBE5hbWUNbmlnaHREdXJhdGlvbgtEZXNjcmlwdGlvbkpPdmVycmlkZSBob3cgbG9uZyB0aGUgYXJlYSBlZ2cgbmlnaHQgbGFzdHMsIG9yIG9taXQgdG8gcmVzdG9yZSB0aGUgZGVmYXVsdAVHcm91cAlNb2RlcmF0b3IEQXJncwRUeXBlBm51bWJlcgdTZWNvbmRzCE9wdGlvbmFsAAEDAAABAgAKowAAAOIABwD/AQAAAQAAAOICDQDFAQICAQAAADABANsGAAAAggACAA4DAQMCAwMDBAMFAwYDBwgEAAEAAAACAwAAAAQFAAAABv////8DCAMJAwoDCwEBCAMICQAAAAAKAAAACwwAAAAAAQABGAAABAABAAD/AAABAAAAAAA4CkfvRgq1iSQvi+8tGnBZSBJQmwrOLe4=

-- decompilation:
return {
	Name = "nightDuration",
	Description = "Override how long the area egg night lasts, or omit to restore the default",
	Group = "Moderator",
	Args = {{
		Type = "number",
		Name = "Seconds",
		Optional = true
	}}
}

