-- Saved by UniversalSynSaveInstance (Join to Copy Games) https://discord.gg/wx4ThpAsmw

-- Bytecode (Base64):
-- CQMNBE5hbWUUcHJvZ3Jlc3NFZ2dIYXRjaFRpbWULRGVzY3JpcHRpb24wSW5jcmVtZW50cyB0aGUgaGF0Y2ggdGltZSBvbiBhbGwgdGhlIHBsYWNlZCBlZ2dzBUdyb3VwCU1vZGVyYXRvcgRBcmdzBFR5cGUHcGxheWVycwdQbGF5ZXJzB2ludGVnZXIGQW1vdW50JFRoZSBhbW91bnQgb2YgaGF0Y2ggdGltZSB0byBwcm9ncmVzcwABBAAAAQIAC6MAAADiAAcA/wEAAAIAAADiAgsA4gMPAMUBAgMBAAAAMAEA2wYAAACCAAIAEAMBAwIDAwMEAwUDBgMHCAQAAQAAAAIDAAAABAUAAAAG/////wMIAwkDCggCCAkAAAAACgAAAAMLAwwDDQgDCAwAAAAADQAAAAIOAAAAAAEAARgAAAQAAQEAAP4AAAEAAAAAAAvrjS6F3Tly+zwWJyL7fT1785paOS/nLw==

-- decompilation:
return {
	Name = "progressEggHatchTime",
	Description = "Increments the hatch time on all the placed eggs",
	Group = "Moderator",
	Args = {
		{
			Type = "players",
			Name = "Players"
		},
		{
			Type = "integer",
			Name = "Amount",
			Description = "The amount of hatch time to progress"
		}
	}
}

