-- Saved by UniversalSynSaveInstance (Join to Copy Games) https://discord.gg/wx4ThpAsmw

-- Bytecode (Base64):
-- CQMHBE5hbWUNcmVzZXRFZ2dDeWNsZQtEZXNjcmlwdGlvbkpEcm9wIHRoaXMgc2VydmVyJ3MgYXJlYSBlZ2cgY3ljbGUgb3ZlcnJpZGVzIGFuZCByZWpvaW4gdGhlIGdsb2JhbCBzY2hlZHVsZQVHcm91cAlNb2RlcmF0b3IEQXJncwABAgAAAQIAB6MAAADiAAcA/wEAAAAAAAAwAQDbBgAAAIIAAgAIAwEDAgMDAwQDBQMGAwcIBAABAAAAAgMAAAAEBQAAAAb/////AAEAARgAAAQAAAAAAQAAAAAA

-- decompilation:
return {
	Name = "resetEggCycle",
	Description = "Drop this server's area egg cycle overrides and rejoin the global schedule",
	Group = "Moderator",
	Args = {}
}

