-- Saved by UniversalSynSaveInstance (Join to Copy Games) https://discord.gg/wx4ThpAsmw

-- Bytecode (Base64):
-- CQMKBE5hbWUJc3RvcEV2ZW50C0Rlc2NyaXB0aW9uDlN0b3BzIGFuIGV2ZW50BUdyb3VwCU1vZGVyYXRvcgRBcmdzBFR5cGUOYWRtaW5FdmVudFR5cGUKRXZlbnQgTmFtZQABAwAAAQIACqMAAADiAAcA/wEAAAEAAADiAgsAxQECAgEAAAAwAQDbBgAAAIIAAgAMAwEDAgMDAwQDBQMGAwcIBAABAAAAAgMAAAAEBQAAAAb/////AwgDCQMKCAIICQAAAAAKAAAAAAEAARgAAAQAAQAA/wAAAQAAAAAA

-- decompilation:
return {
	Name = "stopEvent",
	Description = "Stops an event",
	Group = "Moderator",
	Args = {{
		Type = "adminEventType",
		Name = "Event Name"
	}}
}

