-- Saved by UniversalSynSaveInstance (Join to Copy Games) https://discord.gg/wx4ThpAsmw

-- Bytecode (Base64):
-- CQMIBE5hbWUGdXB0aW1lB0FsaWFzZXMLRGVzY3JpcHRpb243UmV0dXJucyB0aGUgYW1vdW50IG9mIHRpbWUgdGhlIHNlcnZlciBoYXMgYmVlbiBydW5uaW5nLgVHcm91cAxEZWZhdWx0RGVidWcEQXJncwABAgAAAQIAC6MAAADiAAgA/wEAAAAAAAAwAQAnAgAAAP8BAAAAAAAAMAEA2wcAAACCAAIACQMBAwIDAwMEAwUDBgMHAwgIBQABAAAAAv////8DBAAAAAUGAAAAB/////8AAQABGAAAAgAAAAMAAAAAAQAAAAAA

-- decompilation:
return {
	Name = "uptime",
	Description = "Returns the amount of time the server has been running.",
	Group = "DefaultDebug",
	Aliases = {},
	Args = {}
}

