-- Saved by UniversalSynSaveInstance (Join to Copy Games) https://discord.gg/wx4ThpAsmw

-- Bytecode (Base64):
-- CQMLD0NtZHIgVmVyc2lvbiAlcwd2MS4xMi4wBmZvcm1hdANSdW4ETmFtZQd2ZXJzaW9uBEFyZ3MLRGVzY3JpcHRpb24hU2hvd3MgdGhlIGN1cnJlbnQgdmVyc2lvbiBvZiBDbWRyBUdyb3VwDERlZmF1bHREZWJ1ZwACAwAAAAAHAAABAwACAgZvAAAAbwIBALwAAI0CAAAAnwADAIIAAAADAwEDAgMDAAkEARgAAAAAAAAKAAAAAAIAAAECAAqjAAAA4gAIAP8BAAAAAAAAMAEA2wIAAADAAQkAMAEAFgcAAACCAAIACgMFAwYDBwMIAwkDCgMLAwQIBQABAAAAAv////8DBAAAAAUGAAAAB/////8GAAEAAQABGAACAgAAAAQAAAABAAAAAAEVN0Sui3WvNb3XbRGkz86aZS9T2ifzLq8=

-- decompilation:
return {
	Name = "version",
	Description = "Shows the current version of Cmdr",
	Group = "DefaultDebug",
	Args = {},
	Run = function() -- line: 9
		return ("Cmdr Version %s"):format("v1.12.0")
	end
}

