#!/usr/bin/env python3
"""Writes, from the owner's FBX files (assets/hero_weapons/fbx/weapons + fbx/vfx):
  * assets/hero_weapons/fbx_manifest.json   every mesh's name, section, palette and bounds in file space (the build's
                                             synthetic imports for tests, and the checks below);
  * assets/hero_weapons/HeroWeaponsImport.lua  the Studio command-bar helper the owner runs after Import 3D: it checks
                                             each imported model against its FBX (scale, file origin), turns every weapon
                                             into a Tool with the owner's own HeroWeaponTools.Prepare, files the effect
                                             models, and lists what is missing.
Run:  python3 scripts/tools/hero_weapons/gen_import_helper.py
"""
import glob
import json
import os
import sys

HERE = os.path.dirname(os.path.abspath(__file__))
sys.path.insert(0, HERE)
import fbx_inspect as F  # noqa: E402
from rig import ROOT  # noqa: E402

# FBX model name -> the game's weapon id (HeroWeapons.WEAPONS); PowerPole_GoldToy is an alternative Power Pole skin
WEAPON_IDS = {
    "CapShield": "CapShield", "PowerPole": "PowerPole", "PowerPole_GoldToy": "PowerPole_GoldToy",
    "WebShooter": "WebShooter", "Batarang": "Batarang", "Bakugo_Gauntlet": "BakugoGauntlet", "Mjolnir": "Mjolnir",
    "GomuFist": "GomuFist",
}


def mesh_entries(path):
    sc = F.Scene(path)
    entries = []
    for oid, o in sc.models():
        if len(o.props) > 2 and o.props[2] == "Mesh":
            tris, _ = sc.mesh_triangles(oid)
            if tris is None or not len(tris):
                continue
            pts = tris.reshape(-1, 3)
            lo, hi = pts.min(0), pts.max(0)
            name = sc.name_of(oid)
            parts = name.split("__")
            entries.append({
                "name": name,
                "section": parts[1] if len(parts) >= 3 else "Handle",
                "palette": parts[2] if len(parts) >= 3 else None,
                "centre": [round(float(v), 4) for v in (lo + hi) / 2],
                "size": [round(float(v), 4) for v in hi - lo],
                "triangles": int(len(tris)),
            })
    entries.sort(key=lambda e: (e["name"] != "Handle", e["name"]))
    return entries


def lua_vec(v):
    return "{ %s }" % ", ".join(("%g" % x) for x in v)


def main():
    manifest = {"Weapons": {}, "Vfx": {}}
    for path in sorted(glob.glob(os.path.join(ROOT, "assets", "hero_weapons", "fbx", "weapons", "*.fbx"))):
        name = os.path.splitext(os.path.basename(path))[0]
        manifest["Weapons"][name] = {"WeaponId": WEAPON_IDS[name], "Meshes": mesh_entries(path)}
    for path in sorted(glob.glob(os.path.join(ROOT, "assets", "hero_weapons", "fbx", "vfx", "*.fbx"))):
        name = os.path.splitext(os.path.basename(path))[0]
        manifest["Vfx"][name] = {"Meshes": mesh_entries(path)}
    with open(os.path.join(ROOT, "assets", "hero_weapons", "fbx_manifest.json"), "w", newline="\n") as f:
        json.dump(manifest, f, indent=1)
        f.write("\n")

    rows = []
    for kind in ("Weapons", "Vfx"):
        for name, entry in manifest[kind].items():
            handle = next(m for m in entry["Meshes"] if m["name"] == "Handle")
            rows.append('\t["%s"] = { kind = "%s", id = %s, parts = %d, handleCentre = %s, handleSize = %s },' % (
                name, "Weapon" if kind == "Weapons" else "Vfx",
                ('"%s"' % entry["WeaponId"]) if kind == "Weapons" else "nil",
                len(entry["Meshes"]), lua_vec(handle["centre"]), lua_vec(handle["size"])))
    lua = TEMPLATE.replace("--EXPECTED--", "\n".join(rows))
    with open(os.path.join(ROOT, "assets", "hero_weapons", "HeroWeaponsImport.lua"), "w", newline="\n") as f:
        f.write(lua)
    print("wrote fbx_manifest.json (%d weapons, %d vfx) and HeroWeaponsImport.lua" % (len(manifest["Weapons"]), len(manifest["Vfx"])))


TEMPLATE = r'''-- assets/hero_weapons/HeroWeaponsImport.lua  -  Studio command-bar helper for the owner's hero weapon models.
-- GENERATED by scripts/tools/hero_weapons/gen_import_helper.py from assets/hero_weapons/fbx/ (do not edit).
--
-- 1. Open the latest StealaHero.rbxl build in Studio (it holds ReplicatedStorage.Library.Modules.HeroWeaponTools).
-- 2. Import 3D every file of assets/hero_weapons/fbx/weapons (8 weapons) and assets/hero_weapons/fbx/vfx (7 effects).
--    Keep the importer defaults (any position is fine). The Anim_*.fbx files and R15Dummy.fbx are NOT needed: their
--    animations are already in the game (Directory.WeaponAnimations, from the .rbxmx files).
-- 3. Paste this whole file into the command bar (View > Command Bar) and press Enter. For every imported model it
--    finds (the selection, else every Workspace model) it:
--      * matches it to its FBX by name (CapShield, Mjolnir, Web_Cocoon...);
--      * checks its size against the FBX (fixes a unit mismatch with ScaleTo) and its pivot against the file origin
--        (the Handle must sit where the FBX puts it: fixes the pivot if the importer moved it);
--      * weapons: runs the owner's own HeroWeaponTools.Prepare(model, weaponId) and files the Tool in
--        ServerStorage.HeroWeaponImports.Weapons; effects: anchors them, no collisions, files them in
--        ServerStorage.HeroWeaponImports.Vfx; the imported model is removed from Workspace;
--      * prints a checklist of what is still missing.
-- 4. Save the place (Ctrl+S) and send it (or right-click ServerStorage.HeroWeaponImports > Save to File... and send
--    the .rbxm). The next build extracts the imports to assets/hero_weapons/imports/ and every weapon / effect uses
--    them (the part-built stand-ins stay as the fallback for anything not imported).

local EXPECTED = {
--EXPECTED--
}

local ServerStorage = game:GetService("ServerStorage")
local ReplicatedStorage = game:GetService("ReplicatedStorage")
local Selection = game:GetService("Selection")

local function folder(parent, name)
	local f = parent:FindFirstChild(name)
	if not f then
		f = Instance.new("Folder")
		f.Name = name
		f.Parent = parent
	end
	return f
end

local library = ReplicatedStorage:FindFirstChild("Library")
local modules = library and library:FindFirstChild("Modules")
local kitSource = modules and modules:FindFirstChild("HeroWeaponTools")
if not kitSource then
	warn("[HeroWeaponsImport] ReplicatedStorage.Library.Modules.HeroWeaponTools is missing: open the latest StealaHero.rbxl build first.")
	return
end
local kitCopy = kitSource:Clone() -- a fresh copy, so an old cached require never runs
kitCopy.Parent = ServerStorage
local okKit, Kit = pcall(require, kitCopy)
kitCopy:Destroy()
if not okKit then
	warn("[HeroWeaponsImport] HeroWeaponTools failed to load: " .. tostring(Kit))
	return
end

local imports = folder(ServerStorage, "HeroWeaponImports")
local weaponsFolder = folder(imports, "Weapons")
local vfxFolder = folder(imports, "Vfx")

-- longest names first, so "PowerPole_GoldToy" is never taken for "PowerPole"
local names = {}
for name in pairs(EXPECTED) do
	table.insert(names, name)
end
table.sort(names, function(a, b)
	return #a > #b
end)

local function specFor(model)
	for _, name in ipairs(names) do
		if model.Name == name or string.sub(model.Name, 1, #name + 1) == name .. " " then
			return name, EXPECTED[name]
		end
	end
	for _, name in ipairs(names) do
		if model:FindFirstChild(name .. "__", true) then
			return name, EXPECTED[name]
		end
		for _, d in ipairs(model:GetDescendants()) do
			if string.sub(d.Name, 1, #name + 2) == name .. "__" then
				return name, EXPECTED[name]
			end
		end
	end
	return nil, nil
end

local function sortedDims(size)
	local t = { size.X, size.Y, size.Z }
	table.sort(t)
	return t
end

-- Scale and pivot back to the FBX: returns the Handle, or nil + why.
local function normalise(model, spec, notes)
	local handle = model:FindFirstChild("Handle", true)
	if not (handle and handle:IsA("BasePart")) then
		return nil, "no BasePart named Handle"
	end
	local want = sortedDims(Vector3.new(table.unpack(spec.handleSize)))
	local got = sortedDims(handle.Size)
	local ratio = got[3] / math.max(want[3], 1e-3)
	if math.abs(ratio - 1) > 0.05 then
		model:ScaleTo(model:GetScale() / ratio)
		table.insert(notes, string.format("scaled x%.3f to the FBX size", 1 / ratio))
	end
	local pivot = model:GetPivot()
	local expected = Vector3.new(table.unpack(spec.handleCentre))
	local measured = pivot:PointToObjectSpace(handle.Position)
	if (measured - expected).Magnitude > 0.2 then
		model.WorldPivot = CFrame.new(handle.Position) * pivot.Rotation * CFrame.new(-expected)
		table.insert(notes, string.format("pivot moved to the file origin (was %.2f studs off)", (measured - expected).Magnitude))
	end
	return handle
end

local candidates = {}
for _, item in ipairs(Selection:Get()) do
	if item:IsA("Model") then
		table.insert(candidates, item)
	end
end
if #candidates == 0 then
	for _, item in ipairs(workspace:GetChildren()) do
		if item:IsA("Model") then
			table.insert(candidates, item)
		end
	end
end

local filed = {}
for _, model in ipairs(candidates) do
	local name, spec = specFor(model)
	if spec then
		local notes = {}
		local handle, why = normalise(model, spec, notes)
		if not handle then
			warn(string.format("[HeroWeaponsImport] %s: %s - re-import %s.fbx", model.Name, why, name))
		elseif spec.kind == "Weapon" then
			local ok, tool = pcall(Kit.Prepare, model, spec.id)
			if ok then
				tool.Name = spec.id
				tool:SetAttribute("HeroWeaponSource", name .. ".fbx")
				local old = weaponsFolder:FindFirstChild(spec.id)
				if old then
					old:Destroy()
				end
				tool.Parent = weaponsFolder
				model:Destroy()
				filed[name] = true
				print(string.format("[HeroWeaponsImport] %s -> ServerStorage.HeroWeaponImports.Weapons.%s %s", name, spec.id, table.concat(notes, "; ")))
			else
				warn(string.format("[HeroWeaponsImport] %s: Prepare failed: %s", name, tostring(tool)))
			end
		else
			for _, d in ipairs(model:GetDescendants()) do
				if d:IsA("BasePart") then
					d.Anchored = true
					d.CanCollide = false
					d.CanTouch = false
					d.CanQuery = false
					d.CastShadow = false
				elseif d:IsA("Light") or d:IsA("Sound") or d:IsA("LuaSourceContainer") then
					d:Destroy()
				end
			end
			model.Name = name
			model:SetAttribute("HeroWeaponSource", name .. ".fbx")
			local old = vfxFolder:FindFirstChild(name)
			if old then
				old:Destroy()
			end
			model.Parent = vfxFolder
			filed[name] = true
			print(string.format("[HeroWeaponsImport] %s -> ServerStorage.HeroWeaponImports.Vfx.%s %s", name, name, table.concat(notes, "; ")))
		end
	end
end

local missing = {}
for _, name in ipairs(names) do
	local spec = EXPECTED[name]
	local present = if spec.kind == "Weapon" then weaponsFolder:FindFirstChild(spec.id) else vfxFolder:FindFirstChild(name)
	if not present then
		table.insert(missing, name .. ".fbx")
	end
end
table.sort(missing)
if #missing == 0 then
	print("[HeroWeaponsImport] All 15 models are in ServerStorage.HeroWeaponImports. Save the place (Ctrl+S) and send it.")
else
	print("[HeroWeaponsImport] Still missing (Import 3D them, then run this again): " .. table.concat(missing, ", "))
end
'''

if __name__ == "__main__":
    main()
