-- Saved by UniversalSynSaveInstance (Join to Copy Games) https://discord.gg/wx4ThpAsmw

-- Bytecode (Base64):
-- CQMPB3JlcXVpcmUGc2NyaXB0BlBhcmVudAtCdWlsZENvbmZpZwZSYXJpdHkFUHJpY2UJUHJvZHVjdElkBEljb24ccmJ4YXNzZXRpZDovLzEyNTA5NzE3MjE4MDgyNw9TcGVlZE11bHRpcGxpZXINRGlzcGxheUluU2hvcAtEaXNwbGF5TmFtZQpHcmV5IFRyYWlsCFJhcml0aWVzBkNvbW1vbgABBQAAAQIAI6MAAACkAAEAAAAAQKQBAwAAACBATQEBJAQAAABNAQEkBAAAAE0BAeEFAAAAnwACAqQBAQAAAABApAIDAAAAIEBNAgIkBAAAAE0CAiQEAAAATQICJAQAAABNAgLyBgAAAJ8BAgJSAgAA4gMTAE0EAegUAAAATQQEcxUAAAAwBAPyBgAAAJ8CAgCCAgAAFgMBBAAAAEADAgQAACBAAwMDBAMFAwYCAAAAAAAAWUADBwADCAMJAwoCAAAAAAAA+D8DCwEBAwwDDQgHBwgAAAAJCgAAAAsMAAAABv////8NDgAAAA8QAAAAERIAAAADDgMPAAEAARgAAwAAAAAAAAAAAAABAAAAAAAAAAAAAAAAAgAEAAAAAAD8AAEAAAAAAObspr7iYKRDH16QXmB9WuOW9LHK1CjMvw==

-- decompilation:
local BuildConfig = require(script.Parent.Parent.BuildConfig)
local Rarity = require(script.Parent.Parent.Parent.Rarity)

return BuildConfig({
	Price = 200000.0, -- ECON 2026-09-24 (money /125): was 25000000.0; BALANCE 2026-09-23 (owner approved): was 100.0
	ProductId = nil,
	Icon = "rbxassetid://125097172180827",
	SpeedMultiplier = 1.1, -- BALANCE 2026-09-23 (owner approved): was 1.5
	DisplayInShop = true,
	DisplayName = "Grey Trail",
	Rarity = Rarity.Rarities.Common
})

