-- Saved by UniversalSynSaveInstance (Join to Copy Games) https://discord.gg/wx4ThpAsmw

-- Bytecode (Base64):
-- CQMPB3JlcXVpcmUGc2NyaXB0BlBhcmVudAtCdWlsZENvbmZpZwZSYXJpdHkFUHJpY2UJUHJvZHVjdElkBEljb24bcmJ4YXNzZXRpZDovLzk2NzAwODQwMTUxNDg0D1NwZWVkTXVsdGlwbGllcg1EaXNwbGF5SW5TaG9wC0Rpc3BsYXlOYW1lDFB1cnBsZSBUcmFpbAhSYXJpdGllcwRFcGljAAEFAAABAgAjowAAAKQAAQAAAABApAEDAAAAIEBNAQEkBAAAAE0BASQEAAAATQEB4QUAAACfAAICpAEBAAAAAECkAgMAAAAgQE0CAiQEAAAATQICJAQAAABNAgIkBAAAAE0CAvIGAAAAnwECAlICAADiAxMATQQB6BQAAABNBAS8FQAAADAEA/IGAAAAnwICAIICAAAWAwEEAAAAQAMCBAAAIEADAwMEAwUDBgIAAAAAYOM2QQMHAgAAQNyX6OpBAwgDCQMKAgAAAAAAAAhAAwsBAQMMAw0IBwcIAAAACQoAAAALDAAAAAb/////DQ4AAAAPEAAAABESAAAAAw4DDwABAAEYAAMAAAAAAAAAAAAAAQAAAAAAAAAAAAAAAAIABAAAAAAA/AABAAAAAABRvle5Wd5/dD/zqZgyhAwHIaZAzWN6Pbg=

-- decompilation:
local BuildConfig = require(script.Parent.Parent.BuildConfig)
local Rarity = require(script.Parent.Parent.Parent.Rarity)

return BuildConfig({
	Price = 120000000.0, -- ECON 2026-09-24 (money /125): was 15000000000.0; BALANCE 2026-09-23 (owner approved): was 1500000.0
	ProductId = 3611606754.0,
	Icon = "rbxassetid://96700840151484",
	SpeedMultiplier = 1.4, -- BALANCE 2026-09-23 (owner approved): was 3.0
	DisplayInShop = true,
	DisplayName = "Purple Trail",
	Rarity = Rarity.Rarities.Epic
})

