-- Saved by UniversalSynSaveInstance (Join to Copy Games) https://discord.gg/wx4ThpAsmw

-- Bytecode (Base64):
-- CQMMB3JlcXVpcmUGc2NyaXB0BlBhcmVudAVUeXBlcwlJbnRlcmZhY2UJUHJvZHVjdElkC0Rpc3BsYXlOYW1lBUx1Y2t5BEljb24OcmJ4YXNzZXRpZDovLzAERGVzY0BNb3JlIGx1Y2sgdG8gZ2V0IGJldHRlciBwZXRzIGZyb20gYmxvY2tzIGFuZCBmcm9tIGZ1c2UgbWFjaGluZXMhAAECAAABAgAQowAAAKQAAQAAAABApAEDAAAAIEBNAQEkBAAAAE0BASQEAAAATQEB7wUAAABNAQEPBgAAAJ8AAgLiAQ8AggECABADAQQAAABAAwIEAAAgQAMDAwQDBQMGAgAAQBOqoNtBAwcDCAMJAwoDCwMMCAQHCAAAAAkKAAAACwwAAAANDgAAAAABAAEYAAMAAAAAAAAAAAAAAAADBwEAAAAAAEVoWdQJKQfG58pQEpWxZ2I1cE6gd6wz1Q==

-- decompilation:
require(script.Parent.Parent.Types.Interface)

return {
	ProductId = 1854056525.0,
	DisplayName = "Lucky",
	Icon = "rbxassetid://0",
	Desc = "More luck to get better pets from blocks and from fuse machines!"
}

