-- Saved by UniversalSynSaveInstance (Join to Copy Games) https://discord.gg/wx4ThpAsmw

-- Bytecode (Base64):
-- CQMMB3JlcXVpcmUGc2NyaXB0BlBhcmVudAVUeXBlcwlJbnRlcmZhY2UJUHJvZHVjdElkC0Rpc3BsYXlOYW1lCXgyIEdyb3d0aARJY29uDnJieGFzc2V0aWQ6Ly8wBERlc2MTRWdncyBncm93IHgyIGZhc3RlcgABAgAAAQIAEKMAAACkAAEAAAAAQKQBAwAAACBATQEBJAQAAABNAQEkBAAAAE0BAe8FAAAATQEBDwYAAACfAAIC4gEPAIIBAgAQAwEEAAAAQAMCBAAAIEADAwMEAwUDBgIAAEBg98fcQQMHAwgDCQMKAwsDDAgEBwgAAAAJCgAAAAsMAAAADQ4AAAAAAQABGAADAAAAAAAAAAAAAAAAAwcBAAAAAAArkoqvXttAbaJlJzmspUVoW4qd2xlW4K4=

-- decompilation:
require(script.Parent.Parent.Types.Interface)

return {
	ProductId = 1952325300.0,
	DisplayName = "x2 Growth",
	Icon = "rbxassetid://0",
	Desc = "Eggs grow x2 faster"
}

