-- Saved by UniversalSynSaveInstance (Join to Copy Games) https://discord.gg/wx4ThpAsmw

-- Bytecode (Base64):
-- CQMLB3JlcXVpcmUGc2NyaXB0BlBhcmVudAVUeXBlcwlJbnRlcmZhY2UJUHJvZHVjdElkC0Rpc3BsYXlOYW1lCHgyIE1vbmV5BEljb24OcmJ4YXNzZXRpZDovLzAERGVzYwABAgAAAQIAEKMAAACkAAEAAAAAQKQBAwAAACBATQEBJAQAAABNAQEkBAAAAE0BAe8FAAAATQEBDwYAAACfAAIC4gEOAIIBAgAPAwEEAAAAQAMCBAAAIEADAwMEAwUDBgIAAADwltXcQQMHAwgDCQMKAwsIBAcIAAAACQoAAAALDAAAAA0KAAAAAAEAARgAAwAAAAAAAAAAAAAAAAMHAQAAAAAA7GPH202sJVe5LTluX6oSJJx70K/ep63a

-- decompilation:
require(script.Parent.Parent.Types.Interface)

return {
	ProductId = 1955670708.0,
	DisplayName = "x2 Money",
	Icon = "rbxassetid://0",
	Desc = "x2 Money"
}

