-- Saved by UniversalSynSaveInstance (Join to Copy Games) https://discord.gg/wx4ThpAsmw

-- Bytecode (Base64):
-- CQMKBGdhbWURUmVwbGljYXRlZFN0b3JhZ2UKR2V0U2VydmljZQdyZXF1aXJlB0xpYnJhcnkFVHlwZXMJQXNzZXRJdGVtBnNjcmlwdAZQYXJlbnQGU2NoZW1hAAEEAAABAgAaowAAAKQAAQAAAABAbwICALwAABYDAAAAnwADAqQBBQAAAEBATQIAagYAAABNAgLvBwAAAE0CAuYIAAAAnwECAqQCBQAAAEBApAMKAAAAkEBNAwMkCwAAAE0DA/4MAAAAnwICAoICAgANAwEEAAAAQAMCAwMDBAQAAEBAAwUDBgMHAwgEAACQQAMJAwoAAQABGAADAAAAAAADAAAAAAAAAAABAAAAAAAAAABOAQAAAAAA7x0dHG89rU0Z5suEtgucf58FCmjd2Xcd

-- decompilation:
local ReplicatedStorage = game:GetService("ReplicatedStorage")

require(ReplicatedStorage.Library.Types.AssetItem)

return (require(script.Parent.Schema))

