-- Saved by UniversalSynSaveInstance (Join to Copy Games) https://discord.gg/wx4ThpAsmw

-- Bytecode (Base64):
-- CQMFB0RlZmF1bHQLUm9sbE9mZk1vZGUSUm9sbE9mZk1pbkRpc3RhbmNlBEVudW0MTGluZWFyU3F1YXJlAAEDAAABAgAKowAAAOIAAQDiAQUApAIIAAcIYMAwAgFEAgAAADABADoAAAAAggACAAkDAQUBAAMCAwMC/Knx0k1iUD8IAgL/////AwQAAAADBAMFBAcIYMAAAQABGAAAAQEAAAD/AAABAAAAAAA=

-- decompilation:
return {
	Default = {
		RollOffMinDistance = 0.001,
		RollOffMode = Enum.RollOffMode.LinearSquare
	}
}

