-- Saved by UniversalSynSaveInstance (Join to Copy Games) https://discord.gg/wx4ThpAsmw

-- Bytecode (Base64):
-- CQMHBGdhbWURUmVwbGljYXRlZFN0b3JhZ2UKR2V0U2VydmljZQdMaWJyYXJ5B3JlcXVpcmUHTW9kdWxlcw9QaXBlbGluZUJ1aWxkZXIAAQQAAAECABOjAAAApAABAAAAAEBvAgIAvAAAFgMAAACfAAMCTQEAagQAAACkAgYAAABQQE0DAegHAAAATQMD6QgAAACfAgIC/wMAAAAAAACCAwIACQMBBAAAAEADAgMDAwQDBQQAAFBAAwYDBwABAAEYAAEAAAAAAAMAAwAAAAAAADYAAAEAAAAAAA==

-- decompilation:
local Library = game:GetService("ReplicatedStorage").Library

require(Library.Modules.PipelineBuilder)

return {}

