-- Saved by UniversalSynSaveInstance (Join to Copy Games) https://discord.gg/wx4ThpAsmw

-- Bytecode (Base64):
-- CQMPB3JlcXVpcmUGc2NyaXB0BlBhcmVudAtCdWlsZENvbmZpZwZSYXJpdHkFUHJpY2UJUHJvZHVjdElkBEljb24ccmJ4YXNzZXRpZDovLzEzNzA4NjU2NzM1NDc2NQ9TcGVlZE11bHRpcGxpZXINRGlzcGxheUluU2hvcAtEaXNwbGF5TmFtZRFBbmdlbGljIFRyZWFkbWlsbAhSYXJpdGllcwZEaXZpbmUAAQUAAAECACOjAAAApAABAAAAAECkAQMAAAAgQE0BASQEAAAATQEBJAQAAABNAQHhBQAAAJ8AAgKkAQEAAAAAQKQCAwAAACBATQICJAQAAABNAgIkBAAAAE0CAiQEAAAATQIC8gYAAACfAQICUgIAAOIDEwBNBAHoFAAAAE0EBMcVAAAAMAQD8gYAAACfAgIAggIAABYDAQQAAABAAwIEAAAgQAMDAwQDBQMGAgAANCb1awxDAwcCAACA2Zfo6kEDCAMJAwoCAAAAAABAn0ADCwEBAwwDDQgHBwgAAAAJCgAAAAsMAAAABv////8NDgAAAA8QAAAAERIAAAADDgMPAAEAARgAAwAAAAAAAAAAAAABAAAAAAAAAAAAAAAAAgAEAAAAAAD8AAEAAAAAAGozZ0fOTOxrzQBs9zKl2vgaK3AzWPcNRg==

-- decompilation:
local BuildConfig = require(script.Parent.Parent.BuildConfig)
local Rarity = require(script.Parent.Parent.Parent.Rarity)

return BuildConfig({
	Price = 8000000000000.0, -- ECON 2026-09-24 (money /125): was 1000000000000000.0
	ProductId = 3611606732.0,
	Icon = "rbxassetid://137086567354765",
	SpeedMultiplier = 2560.0, -- BALANCE 2026-09-23 (owner approved): the MODDED x3 reverted (was 6000.0)
	DisplayInShop = true,
	DisplayName = "Angelic Treadmill",
	Rarity = Rarity.Rarities.Divine
})

