-- Saved by UniversalSynSaveInstance (Join to Copy Games) https://discord.gg/wx4ThpAsmw

-- Bytecode (Base64):
-- CQMPB3JlcXVpcmUGc2NyaXB0BlBhcmVudAtCdWlsZENvbmZpZwZSYXJpdHkFUHJpY2UJUHJvZHVjdElkBEljb24ccmJ4YXNzZXRpZDovLzEyOTAxOTc5NjIyMzMwMg9TcGVlZE11bHRpcGxpZXINRGlzcGxheUluU2hvcAtEaXNwbGF5TmFtZQlUcmVhZG1pbGwIUmFyaXRpZXMGQ29tbW9uAAEFAAABAgAjowAAAKQAAQAAAABApAEDAAAAIEBNAQEkBAAAAE0BASQEAAAATQEB4QUAAACfAAICpAEBAAAAAECkAgMAAAAgQE0CAiQEAAAATQICJAQAAABNAgIkBAAAAE0CAvIGAAAAnwECAlICAADiAxMATQQB6BQAAABNBARzFQAAADAEA/IGAAAAnwICAIICAAAWAwEEAAAAQAMCBAAAIEADAwMEAwUDBgIAAAAAAAAAAAMHAAMIAwkDCgIAAAAAAAAAQAMLAQEDDAMNCAcHCAAAAAkKAAAACwwAAAAG/////w0OAAAADxAAAAAREgAAAAMOAw8AAQABGAADAAAAAAAAAAAAAAEAAAAAAAAAAAAAAAACAAQAAAAAAPwAAQAAAAAAPM+/OJzOzBh3Z6wZl7xn/EzXqEwOC9U5

-- decompilation:
local BuildConfig = require(script.Parent.Parent.BuildConfig)
local Rarity = require(script.Parent.Parent.Parent.Rarity)

return BuildConfig({
	Price = 0.0,
	ProductId = nil,
	Icon = "rbxassetid://129019796223302",
	SpeedMultiplier = 2.0, -- BALANCE 2026-09-23 (owner approved): the MODDED x3 reverted (was 6.0)
	DisplayInShop = true,
	DisplayName = "Treadmill",
	Rarity = Rarity.Rarities.Common
})

