-- Saved by UniversalSynSaveInstance (Join to Copy Games) https://discord.gg/wx4ThpAsmw

-- Bytecode (Base64):
-- CQMOBGdhbWURUmVwbGljYXRlZFN0b3JhZ2UKR2V0U2VydmljZQdyZXF1aXJlCURpcmVjdG9yeQpBbmltYXRpb25zCFBpcGVsaW5lB0xpYnJhcnkJRnVuY3Rpb25zEERlZXBGcmVlemVVbnNhZmUKRHJvcFdlaWdodAZMb29wZWQEUGxheQRTdG9wAAEHAAABAgArowAAAKQAAQAAAABAbwICALwAABYDAAAAnwADAqQBBQAAAEBATQIAkQYAAABNAgJEBwAAAE0CAjkIAAAAnwECAqQCBQAAAEBATQMAagkAAABNAwNTCgAAAE0DAzALAAAAnwICAlIDAgDiBBIA/wUAAAEAAABvBhMAxQUGAgEAAAAwBQTuEAAAAP8FAAABAAAAbwYUAMUFBgIBAAAAMAUE+hEAAACfAwICggMCABUDAQQAAABAAwIDAwMEBAAAQEADBQMGAwcDCAMJAwoDCwIAAAAAAADwPwMMAQEDDQMOCAQMDQAAAA4PAAAAEP////8R/////wIzMzMzMzPDPwIAAAAAAADgPwABAAEYAAMAAAAAAAMAAAAAAAAAAAEAAAAAAAAAAAMAAwABAAD/AAMAAQAA/wD6AAEAAAAAAFoAja3kicq3LHwYk5A7NXEqGJrZaMTnrA==

-- decompilation:
local ReplicatedStorage = game:GetService("ReplicatedStorage")

require(ReplicatedStorage.Directory.Animations.Pipeline)

return (require(ReplicatedStorage.Library.Functions.DeepFreezeUnsafe)({
	DropWeight = 1.0,
	Looped = true,
	Play = { 0.15 },
	Stop = { 0.5 }
}))

