-- Saved by UniversalSynSaveInstance (Join to Copy Games) https://discord.gg/wx4ThpAsmw

-- Bytecode (Base64):
-- CQMFB3JlcXVpcmUGc2NyaXB0BlBhcmVudAZTY2hlbWEGUmFyaXR5AAEDAAABAgAYowAAAKQAAQAAAABApAEDAAAAIEBNAQEkBAAAAE0BAf4FAAAAnwACAqQBAQAAAABApAIDAAAAIEBNAgIkBAAAAE0CAiQEAAAATQICJAQAAABNAgLyBgAAAJ8BAgKCAAIABwMBBAAAAEADAgQAACBAAwMDBAMFAAEAARgAAwAAAAAAAAAAAQAAAAAAAAAAAAAAAA4BAAAAAAA=

-- decompilation:
local Schema = require(script.Parent.Schema)

require(script.Parent.Parent.Parent.Rarity)

return Schema

