-- Saved by UniversalSynSaveInstance (Join to Copy Games) https://discord.gg/wx4ThpAsmw

-- Bytecode (Base64):
-- CQMMBGdhbWURUmVwbGljYXRlZFN0b3JhZ2UKR2V0U2VydmljZQdyZXF1aXJlBnNjcmlwdAZQYXJlbnQGU2NoZW1hC1BlcnNvbmFsaXR5B0xpYnJhcnkFQXVkaW8JRGlyZWN0b3J5BlJhcml0eQABBgAAAQIAKKMAAACkAAEAAAAAQG8CAgC8AAAWAwAAAJ8AAwKkAQUAAABAQKQCBwAAAGBATQICJAgAAABNAgL+CQAAAJ8BAgKkAgUAAABAQKQDBwAAAGBATQMDJAgAAABNAwMeCgAAAJ8CAgKkAwUAAABAQE0EAGoLAAAATQQE0gwAAACfAwICpAQFAAAAQEBNBQCRDQAAAE0FBfIOAAAAnwQCAoIBAgAPAwEEAAAAQAMCAwMDBAQAAEBAAwUEAABgQAMGAwcDCAMJAwoDCwMMAAEAARgAAwAAAAAAAwAAAAAAAAAAAQAAAAAAAAAAAQAAAAAAAAEAAAAAAAA9AQAAAAAAXYpS2dKn2PLrCQYWacW++i2SRa1vTjjY

-- decompilation:
local ReplicatedStorage = game:GetService("ReplicatedStorage")
local Schema = require(script.Parent.Schema)

require(script.Parent.Personality)
require(ReplicatedStorage.Library.Audio)
require(ReplicatedStorage.Directory.Rarity)

return Schema

