-- Saved by UniversalSynSaveInstance (Join to Copy Games) https://discord.gg/wx4ThpAsmw

-- Bytecode (Base64):
-- CQMFB3JlcXVpcmUGc2NyaXB0BlBhcmVudAhJbnRlcm5hbB1DcmVhdGVMaW1pdGVkRWdnUHJvZHVjdENvbmZpZwABBAAAAQIAFaMAAACkAAEAAAAAQKQBAwAAACBATQEBJAQAAABNAQEkBAAAAE0BASQEAAAATQEBpQUAAABNAQGfBgAAAJ8AAgJSAQAAbwIHAIwDCgCfAQMAggEAAAgDAQQAAABAAwIEAAAgQAMDAwQDBQIAAIDjl+jqQQABAAEYAAMAAAAAAAAAAAAAAAAAAAIAAAAAAQAAAAAA

-- decompilation:
return require(script.Parent.Parent.Parent.Internal.CreateLimitedEggProductConfig)(3709337951.0, 10.0)

