-- assets/models/bases/BaseThemesImport.lua  -  Studio command bar helper for the Blender-modelled base themes.
-- GENERATED by scripts/tools/blender/base_themes/run.py from every assets/models/bases/<Key>/<Name>.json (do not edit).
--
-- 1. Studio: Avatar (or Home) > Import 3D > assets/models/bases/<Key>/<Name>.fbx (one per theme; each file holds both
--    pen variants, "Std_*" and "Deep_*" parts, overlapping at the origin). Keep the importer defaults; any scale /
--    position / yaw is fine (the build normalises them from the floor and the terminal). Import as many themes as
--    you like before step 2.
-- 2. Paste this whole file into the command bar (View > Command Bar) and press Enter. It finds the imported models
--    (the selection, else every Workspace model), recognises each theme by its model name (else by its part names),
--    applies the palette (one colour + material per material family mesh: Structure_* / Floor_* / Core_3D_* /
--    Neon_Emissive_* = the accent colours, NOT emissive: no Neon and no lights in the bases, owner 2026-09-25),
--    anchors the parts, turns collisions / queries / touches off, removes any light, stamps the theme's geometry
--    fingerprint (attribute GeometryFingerprint: the build uses the import only while the layout's geometry is the
--    one you imported; after a geometry change it logs "re-import <Name>.fbx") and moves each model to
--    ServerStorage.BaseThemeImports.<Key> as <Name>.
-- 3. Save the place (Ctrl+S on StealaHero.rbxl: the next build extracts ServerStorage.BaseThemeImports to
--    assets/models/bases/<Key>/<Name>.rbxm before it overwrites the file), or right-click each model > Save to
--    File... as assets/models/bases/<Key>/<Name>.rbxm. Rebuild: every plot where a pen fits gets it
--    (scripts/steps/post_zz_base_themes.luau, section 4).
-- Themes marked legacy = true come from the old (v2) layouts made before the 2026-09-24 art direction: the build
-- ignores them until their theme is rebuilt on the v3 API (the helper still files them, and says so).

local THEMES = {
	{ key = "Forest", name = "StarkLab", title = "Stark Lab", legacy = false, prefixes = { "Std_", "Deep_" }, fingerprint = "g1:ca6a3f785e7fdcafc7ba0fd0",
		anchors = { Floor_Base = true, Neon_Emissive_Screen = true }, palette = {
		Core_3D_Graphite = { 55, 65, 74, "SmoothPlastic", 0, 0 },
		Core_3D_Silver = { 184, 197, 204, "SmoothPlastic", 0, 0.045 },
		Floor_Base = { 87, 93, 101, "SmoothPlastic", 0, 0 },
		Neon_Emissive_Architectural = { 132, 184, 214, "SmoothPlastic", 0, 0.06 },
		Neon_Emissive_Screen = { 96, 166, 204, "SmoothPlastic", 0, 0.06 },
		Structure_Glazing = { 91, 132, 151, "Glass", 0.28, 0.1 },
		Structure_Graphite = { 36, 44, 53, "SmoothPlastic", 0, 0 },
		Structure_Steel = { 149, 161, 172, "SmoothPlastic", 0, 0.045 },
	} },
	{ key = "Lake", name = "HallOfJustice", title = "Hall of Justice", legacy = false, prefixes = { "Std_", "Deep_" }, fingerprint = "g1:569a514400463b4a96432b98",
		anchors = { Floor_Base = true, Neon_Emissive_Screen = true }, palette = {
		Core_3D_Blue = { 30, 64, 160, "SmoothPlastic", 0, 0 },
		Core_3D_Flame = { 232, 80, 36, "SmoothPlastic", 0, 0 },
		Core_3D_Gold = { 246, 190, 58, "SmoothPlastic", 0, 0.06 },
		Floor_Base = { 226, 214, 188, "SmoothPlastic", 0, 0 },
		Floor_Grey = { 198, 190, 172, "SmoothPlastic", 0, 0 },
		Floor_Lawn = { 104, 174, 84, "Plastic", 0, 0 },
		Floor_Walk = { 247, 244, 235, "SmoothPlastic", 0, 0 },
		Floor_Water = { 104, 186, 236, "SmoothPlastic", 0, 0.12 },
		Neon_Emissive_Sapphire = { 40, 76, 156, "SmoothPlastic", 0, 0.12 },
		Neon_Emissive_Screen = { 240, 188, 64, "SmoothPlastic", 0, 0.06 },
		Structure_Bark = { 116, 88, 66, "Plastic", 0, 0 },
		Structure_Blue = { 30, 50, 112, "SmoothPlastic", 0, 0 },
		Structure_Gold = { 238, 184, 62, "SmoothPlastic", 0, 0.06 },
		Structure_Leaf = { 62, 132, 72, "Plastic", 0, 0 },
		Structure_Marble = { 238, 228, 204, "SmoothPlastic", 0, 0 },
	} },
	{ key = "Desert", name = "BrooklynRooftop", title = "Brooklyn Rooftop", legacy = false, prefixes = { "Std_", "Deep_" }, fingerprint = "g1:ebec55f7dbb19703dab32927",
		anchors = { Floor_Base = true, Neon_Emissive_Screen = true }, palette = {
		Core_3D_Black = { 24, 24, 32, "SmoothPlastic", 0, 0 },
		Core_3D_Metal = { 150, 160, 174, "SmoothPlastic", 0, 0.1 },
		Core_3D_Red = { 214, 30, 44, "SmoothPlastic", 0, 0 },
		Core_3D_White = { 238, 240, 246, "SmoothPlastic", 0, 0 },
		Core_3D_Yellow = { 255, 206, 46, "SmoothPlastic", 0, 0 },
		Floor_Base = { 58, 60, 72, "Plastic", 0, 0 },
		Neon_Emissive_Cyan = { 30, 190, 212, "SmoothPlastic", 0, 0.05 },
		Neon_Emissive_Magenta = { 232, 58, 152, "SmoothPlastic", 0, 0.05 },
		Neon_Emissive_Screen = { 232, 58, 152, "SmoothPlastic", 0, 0.06 },
		Structure_Brick = { 176, 60, 46, "SmoothPlastic", 0, 0 },
		Structure_BrickDark = { 104, 38, 36, "SmoothPlastic", 0, 0 },
		Structure_Concrete = { 218, 210, 194, "SmoothPlastic", 0, 0 },
		Structure_Iron = { 30, 30, 38, "SmoothPlastic", 0, 0.04 },
		Structure_Steel = { 66, 84, 118, "SmoothPlastic", 0, 0.04 },
		Structure_Wood = { 150, 98, 60, "SmoothPlastic", 0, 0 },
	} },
	{ key = "Jungle", name = "UAHeroArena", title = "U.A. Hero Arena", legacy = false, prefixes = { "Std_", "Deep_" }, fingerprint = "g1:179eac05ebb42d26dd3e532c",
		anchors = { Floor_Base = true, Neon_Emissive_Screen = true }, palette = {
		Core_3D_Gold = { 244, 200, 42, "SmoothPlastic", 0, 0.06 },
		Core_3D_Navy = { 20, 32, 78, "SmoothPlastic", 0, 0 },
		Core_3D_White = { 248, 248, 250, "SmoothPlastic", 0, 0 },
		Floor_Base = { 222, 221, 214, "Plastic", 0, 0 },
		Floor_Turf = { 92, 168, 76, "Plastic", 0, 0 },
		Floor_White = { 246, 246, 243, "SmoothPlastic", 0, 0 },
		Neon_Emissive_Green = { 64, 158, 146, "SmoothPlastic", 0, 0.08 },
		Neon_Emissive_Lamp = { 74, 146, 222, "SmoothPlastic", 0, 0.1 },
		Neon_Emissive_Screen = { 244, 200, 42, "SmoothPlastic", 0, 0.06 },
		Structure_Beige = { 228, 214, 168, "SmoothPlastic", 0, 0 },
		Structure_Glass = { 24, 74, 180, "SmoothPlastic", 0, 0.14 },
		Structure_Navy = { 46, 70, 206, "SmoothPlastic", 0, 0.03 },
		Structure_Red = { 178, 88, 64, "Plastic", 0, 0 },
		Structure_Silver = { 196, 202, 212, "SmoothPlastic", 0, 0 },
		Structure_White = { 244, 246, 250, "SmoothPlastic", 0, 0 },
	} },
	{ key = "Snow", name = "CapsuleCorp", title = "Capsule Corp Arena", legacy = false, prefixes = { "Std_", "Deep_" }, fingerprint = "g1:02b7a6e0390c2d9f8dac6d5a",
		anchors = { Floor_Base = true, Neon_Emissive_Screen = true }, palette = {
		Core_3D_Amber = { 255, 132, 0, "SmoothPlastic", 0, 0.12 },
		Core_3D_Red = { 200, 14, 24, "SmoothPlastic", 0, 0 },
		Floor_Base = { 66, 168, 48, "Plastic", 0, 0 },
		Floor_Stone = { 82, 78, 76, "Plastic", 0, 0 },
		Floor_Tile = { 178, 172, 160, "Plastic", 0, 0 },
		Neon_Emissive_Screen = { 62, 216, 100, "SmoothPlastic", 0, 0.05 },
		Neon_Emissive_Teal = { 40, 214, 206, "SmoothPlastic", 0, 0.05 },
		Structure_Navy = { 30, 50, 104, "SmoothPlastic", 0, 0 },
		Structure_Orange = { 255, 112, 10, "SmoothPlastic", 0, 0.04 },
		Structure_Pearl = { 246, 244, 236, "SmoothPlastic", 0, 0 },
		Structure_Radar = { 22, 90, 54, "SmoothPlastic", 0, 0 },
		Structure_Teal = { 18, 184, 196, "SmoothPlastic", 0, 0 },
	} },
	{ key = "Volcano", name = "SunnyPirateWharf", title = "Sunny Pirate Wharf", legacy = false, prefixes = { "Std_", "Deep_" }, fingerprint = "g1:37754577e17381b3a4036532",
		anchors = { Floor_Base = true, Neon_Emissive_Screen = true }, palette = {
		Core_3D_Gold = { 250, 196, 70, "SmoothPlastic", 0, 0.06 },
		Core_3D_Ivory = { 246, 234, 208, "SmoothPlastic", 0, 0 },
		Core_3D_SunnyAft_Ivory = { 246, 240, 226, "Plastic", 0, 0 },
		Core_3D_SunnyAft_Wood = { 30, 28, 30, "SmoothPlastic", 0, 0 },
		Core_3D_SunnyFlag_Ivory = { 250, 250, 248, "SmoothPlastic", 0, 0 },
		Core_3D_SunnyFlag_Wood = { 30, 28, 30, "SmoothPlastic", 0, 0 },
		Core_3D_SunnyHull_Gold = { 255, 208, 64, "SmoothPlastic", 0, 0.03 },
		Core_3D_SunnyHull_Ivory = { 244, 234, 210, "SmoothPlastic", 0, 0 },
		Core_3D_SunnyHull_Orange = { 240, 122, 36, "SmoothPlastic", 0, 0 },
		Core_3D_SunnyHull_Wood = { 34, 30, 32, "SmoothPlastic", 0, 0 },
		Core_3D_SunnyMain_Gold = { 248, 200, 74, "SmoothPlastic", 0, 0 },
		Core_3D_SunnyMain_Ivory = { 252, 251, 247, "SmoothPlastic", 0, 0 },
		Core_3D_SunnyMain_Sail = { 236, 224, 196, "Plastic", 0, 0 },
		Core_3D_SunnyMain_Wood = { 30, 28, 30, "SmoothPlastic", 0, 0 },
		Core_3D_Wood = { 58, 40, 32, "SmoothPlastic", 0, 0 },
		Floor_Base = { 228, 182, 118, "SmoothPlastic", 0, 0 },
		Floor_Dark = { 104, 62, 38, "SmoothPlastic", 0, 0 },
		Floor_Iron = { 58, 52, 52, "SmoothPlastic", 0, 0 },
		Floor_Teak = { 204, 148, 88, "SmoothPlastic", 0, 0 },
		Neon_Emissive_Lantern = { 250, 164, 52, "SmoothPlastic", 0, 0.08 },
		Neon_Emissive_Screen = { 250, 164, 52, "SmoothPlastic", 0, 0.08 },
		Structure_Bronze = { 226, 160, 62, "SmoothPlastic", 0, 0.08 },
		Structure_Plank = { 178, 88, 48, "SmoothPlastic", 0, 0 },
		Structure_Red = { 204, 36, 42, "SmoothPlastic", 0, 0 },
		Structure_Rope = { 236, 206, 142, "Plastic", 0, 0 },
		Structure_SunnyAft_Red = { 200, 44, 42, "Plastic", 0, 0 },
		Structure_SunnyAft_Wood = { 104, 64, 40, "SmoothPlastic", 0, 0 },
		Structure_SunnyHull_Grass = { 96, 168, 72, "SmoothPlastic", 0, 0 },
		Structure_SunnyHull_Plank = { 116, 68, 40, "SmoothPlastic", 0, 0 },
		Structure_SunnyHull_Red = { 198, 44, 42, "SmoothPlastic", 0, 0 },
		Structure_SunnyHull_Rope = { 176, 132, 84, "Plastic", 0, 0 },
		Structure_SunnyHull_Wood = { 104, 64, 40, "SmoothPlastic", 0, 0 },
		Structure_SunnyMain_Red = { 206, 40, 40, "SmoothPlastic", 0, 0 },
		Structure_SunnyMain_Wood = { 104, 64, 40, "SmoothPlastic", 0, 0 },
		Structure_Wood = { 98, 58, 36, "SmoothPlastic", 0, 0 },
	} },
}

local ServerStorage = game:GetService("ServerStorage")
local Selection = game:GetService("Selection")

local function norm(s)
	return (string.gsub(string.lower(s), "[^%w]", ""))
end

-- the theme role of a part name: variant prefix stripped, the longest palette role it contains
local function roleOf(theme, name)
	local rest = name
	for _, prefix in ipairs(theme.prefixes) do
		if string.lower(string.sub(name, 1, #prefix)) == string.lower(prefix) then
			rest = string.sub(name, #prefix + 1)
			break
		end
	end
	local best
	for role in pairs(theme.palette) do
		if string.find(string.lower(rest), string.lower(role), 1, true) and (best == nil or #role > #best) then
			best = role
		end
	end
	return best
end

local function hasPrefix(theme, name)
	for _, prefix in ipairs(theme.prefixes) do
		if string.lower(string.sub(name, 1, #prefix)) == string.lower(prefix) then
			return true
		end
	end
	return false
end

-- the theme of an imported model: by its name ("StarkLab", "StarkLab.fbx", ...; the longest theme name it contains), else
-- by its parts (the theme whose own roles, not the shared anchors, name the most "Std_*" / "Deep_*" parts); nil for
-- anything that is not an import
local function detect(model)
	local key = norm(model.Name)
	local named, best, bestScore = nil, nil, 0
	for _, theme in ipairs(THEMES) do
		local score, prefixed = 0, 0
		for _, d in ipairs(model:GetDescendants()) do
			if d:IsA("BasePart") and hasPrefix(theme, d.Name) then
				prefixed += 1
				local role = roleOf(theme, d.Name)
				if role and not theme.anchors[role] then
					score += 1
				end
			end
		end
		if prefixed > 0 and string.find(key, norm(theme.name), 1, true) and (named == nil or #theme.name > #named.name) then
			named = theme
		end
		if score > bestScore then
			best, bestScore = theme, score
		end
	end
	if named then
		return named
	end
	return if bestScore >= 3 then best else nil
end

local picked = Selection:Get()
local candidates = {}
for _, inst in ipairs(if #picked > 0 then picked else workspace:GetChildren()) do
	if inst:IsA("Model") and not inst:FindFirstChildOfClass("Humanoid") then
		local theme = detect(inst)
		if theme then
			table.insert(candidates, { inst, theme })
		end
	end
end
if #candidates == 0 then
	warn("[BaseThemesImport] no imported base theme found: select the imported model(s) (or leave them in Workspace) and run again")
	return
end

local imports = ServerStorage:FindFirstChild("BaseThemeImports") or Instance.new("Folder")
imports.Name = "BaseThemeImports"
imports.Parent = ServerStorage
for _, entry in ipairs(candidates) do
	local model, theme = entry[1], entry[2]
	local folder = imports:FindFirstChild(theme.key) or Instance.new("Folder")
	folder.Name = theme.key
	folder.Parent = imports
	local styled, unknown, perPrefix = 0, 0, {}
	for _, d in ipairs(model:GetDescendants()) do
		if d:IsA("SurfaceAppearance") or d:IsA("Light") then
			d:Destroy()
		elseif d:IsA("BasePart") then
			local role = roleOf(theme, d.Name)
			local look = role and theme.palette[role]
			if look then
				d.Color = Color3.fromRGB(look[1], look[2], look[3])
				d.Material = Enum.Material[look[4]] -- SmoothPlastic / Plastic / Glass only: no neon in a base (2026-09-25)
				d.Transparency = look[5]
				d.Reflectance = look[6]
				d.CastShadow = look[5] < 0.5
				styled += 1
				for _, prefix in ipairs(theme.prefixes) do
					if string.lower(string.sub(d.Name, 1, #prefix)) == string.lower(prefix) then
						perPrefix[prefix] = (perPrefix[prefix] or 0) + 1
					end
				end
			else
				unknown += 1
			end
			d.Anchored = true
			d.CanCollide = false
			d.CanQuery = false
			d.CanTouch = false
		end
	end
	local old = folder:FindFirstChild(theme.name)
	if old and old ~= model then
		old:Destroy()
	end
	model.Name = theme.name
	model:SetAttribute("GeometryFingerprint", theme.fingerprint)
	model:SetAttribute("ImportedFrom", theme.name .. ".fbx")
	model.Parent = folder
	local counts = {}
	for _, prefix in ipairs(theme.prefixes) do
		table.insert(counts, string.format("%s%d", prefix, perPrefix[prefix] or 0))
	end
	print(string.format("[BaseThemesImport] %s (%s) -> ServerStorage.BaseThemeImports.%s.%s: %d parts styled (%s), %d unknown, geometry %s",
		theme.title, theme.key, theme.key, theme.name, styled, table.concat(counts, " "), unknown, theme.fingerprint))
	if theme.legacy then
		warn(string.format("[BaseThemesImport] %s is a LEGACY (v2) layout: the build ignores it until themes/%s.py is rebuilt on the v3 API",
			theme.name, string.lower(theme.key)))
	end
end
print("[BaseThemesImport] done: save the place (Ctrl+S) or Save to File each model as assets/models/bases/<Key>/<Name>.rbxm, then rebuild")
